- hosts: localhost
  tasks:
    - add_host: hostname=deploy_host ansible_ssh_host={{ HOST }} ansible_ssh_port={{ PORT }} ansible_ssh_user=www

- hosts: deploy_host
  tasks:
    - file: dest=/data/www/shared/Data/Persistent state=directory owner=80 group=80
      become: true
    - synchronize:
        src: Persistent/
        dest: /data/www/shared/Data/Persistent/
        rsync_opts:
          - "-q"
          - "--recursive"
          - "--times"
          - "--perms"
          - "--links"
          - "--delete"
          - "--delete-excluded"
    - name: Create database
      shell: echo "CREATE DATABASE IF NOT EXISTS db" | mysql -u admin -ppass -h db
    - name: Import database
      shell: mysql -u admin -ppass -h db db < /data/www/shared/Data/Persistent/db.sql
